### ISSUE TITLE
d(9, 16, 25) is not a list

### ISSUE THREAD

**Issue by dmenne** [jennybc/purrr-tutorial#6]
Hi, Jenny,

I like your tutorials a lot, and have used it for myself and my students multiple time. My comment refers to

https://jennybc.github.io/purrr-tutorial/ls01_map-name-position-shortcuts.html

> purrr::map() is a function for applying a function to each element of a list. The closest base R function is lapply(). Here’s how the square root example of the above would look if the input was in a list. 

```
is.list(c(1,2,3))
[1] FALSE
is.vector(c(1,2,3))
[1] TRUE
```

Mmm... I remember that I when I started using R in 1999, I needed x years (won't solve for x here to protect the innocent) to realize that I can use `lapply(c(1,2,3),...)`; I never had the idea that this could be possible, because c(1,2,3) is a vector, not a list. I admit having seen it many times in the example, but nobody told me the truth where the list comes from.

So I think your example is a bit misleading. It assumes that `c(9,16,25)` in fact has an implicit `as.list(c..)`, and that should be made clear. Suggested
```
mylist = as.list(c(9, 16, 25))
map(mylist, sqrt)
### surprise
map(c(9, 16, 25), sqrt)
## Uh....
```

**Comment by jennybc** [comment]
`purrr::map()` works on vectors (including lists). If I have a wording problem, I think it is more in that direction.

``` r
x <- c(9, 16, 25)
purrr::map(x, sqrt)
#> [[1]]
#> [1] 3
#> 
#> [[2]]
#> [1] 4
#> 
#> [[3]]
#> [1] 5
x_list <- as.list(x)
purrr::map(x_list, sqrt)
#> [[1]]
#> [1] 3
#> 
#> [[2]]
#> [1] 4
#> 
#> [[3]]
#> [1] 5
```

Created on 2018-08-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by dmenne** [comment]
purrr::map() is a function for applying a function to each element of a list __or a vector__ ?
